version: 0.2

phases:
  build:
    commands:
      - echo "No build step required for this project"
  post_build:
    commands:
      - aws s3 cp . s3://obs.streamigniter.gg/ --recursive --exclude "buildspec.yml"

artifacts:
  files:
    - '**/*'
